function MenuLeft() {
document.write("<div id='menu'>")
document.write("<h2>Platform</h2>")
document.write("<div><a href='index.html#START1'>About the platform</a></div>")
document.write("<div><a href='mission.html#START1'>Mission</a></div>")
document.write("<div><a href='descript.html#START2'>Platform description</a></div>")
document.write("<div><a href='descript.html#START3'>Technical requirements</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Installation</h2>")
document.write("<div><a href='install.html#INSTALL1'>Downloading archive</a></div>")
document.write("<div><a href='install.html#INSTALL2'>Installation on site</a></div>")
document.write("<div><a href='install.html#INSTALL2'>Site settings</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Applications</h2>")
document.write("<div><a href='apps.html#MACOS'>MacOS, iOS</a></div>")
document.write("<div><a href='apps.html#ANDROID'>Android</a></div>")
document.write("<div><a href='apps.html#WINDOWS'>Windows</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Documentation</h2>")
document.write("<div><a href='guide.html#GUIDE1'>Introduction</a></div>")
document.write("<div><a href='guide.html#GUIDE2'>Family Member List</a></div>")
document.write("<div><a href='guide.html#GUIDE3'>Creating a New and Updating a Card</a></div>")
document.write("<div><a href='guide.html#GUIDE4'>Entering the Mother/Father Field</a></div>")
document.write("<div><a href='guide.html#GUIDE5'>Entering the Field Spouse</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>License</h2>")
document.write("<div><a href='privacy.html#PRIVACY'>Privacy Policy</a></div>")
document.write("<div><a href='donate.html#DONATE'>Donations</a></div>")
document.write("</div>")
}