function MenuLeft() {
document.write("<div id='menu'>")
document.write("<h2>Plattform</h2>")
document.write("<div><a href='index.html#START1'>Über die Plattform</a></div>")
document.write("<div><a href='mission.html#START1'>Mission</a></div>")
document.write("<div><a href='descript.html#START2'>Plattformbeschreibung</a></div>")
document.write("<div><a href='descript.html#START3'>Technische Anforderungen</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Installation</h2>")
document.write("<div><a <a href='install.html#INSTALL1'>Archiv wird heruntergeladen</a></div>")
document.write("<div><a href='install.html#INSTALL2'>Installation vor Ort</a></div>")
document.write("<div><a href='install.html#INSTALL2'>Website-Einstellungen</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Anwendungen</h2>")
document.write("<div><a href='apps.html#MACOS'>MacOS, iOS</a></div>")
document.write("<div><a href='apps.html#ANDROID'>Android</a></div>")
document.write("<div><a <a href='apps.html#WINDOWS'>Windows</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Dokumentation</h2>")
document.write("<div><a href='guide.html#GUIDE1'>Einführung</a></div>")
document.write("<div><a href='guide.html#GUIDE2'>Familienmitgliederliste</a></div>")
document.write("<div><a href='guide.html#GUIDE3'>Erstellen und Aktualisieren einer Karte</a></div>")
document.write("<div><a href='guide.html#GUIDE4'>Eingeben des Feldes Mutter/Vater</a></div>")
document.write("<div><a <a href='guide.html#GUIDE5'>Eingabe des Feldes Ehepartner</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Lizenz</h2>")
document.write("<div><a href='privacy.html#PRIVACY'>Datenschutzrichtlinie</a></div>")
document.write("<div><a href='donate.html#DONATE'>Spenden</a></div>")
document.write("</div>")
}