function MenuLeft() {
document.write("<div id='menu'>")
document.write("<h2>Piattaforma</h2>")
document.write("<div><a href='index.html#START1'>Informazioni sulla piattaforma</a></div>")
document.write("<div><a href='mission.html#START1'>Missione</a></div>")
document.write("<div><a href='descript.html#START2'>Descrizione della piattaforma</a></div>")
document.write("<div><a href='descript.html#START3'>Requisiti tecnici</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Installazione</h2>")
document.write("<div><a href='install.html#INSTALL1'>Download archivio</a></div>")
document.write("<div><a href='install.html#INSTALL2'>Installazione sul sito</a></div>")
document.write("<div><a href='install.html#INSTALL2'>Impostazioni sito</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Applicazioni</h2>")
document.write("<div><a href='apps.html#MACOS'>MacOS, iOS</a></div>")
document.write("<div><a href='apps.html#ANDROID'>Android</a></div>")
document.write("<div><a href='apps.html#WINDOWS'>Windows</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Documentazione</h2>")
document.write("<div><a href='guide.html#GUIDE1'>Introduzione</a></div>")
document.write("<div><a href='guide.html#GUIDE2'>Elenco dei membri della famiglia</a></div>")
document.write("<div><a href='guide.html#GUIDE3'>Creazione di una nuova scheda e aggiornamento di una scheda</a></div>")
document.write("<div><a href='guide.html#GUIDE4'>Inserimento del campo Madre/Padre</a></div>")
document.write("<div><a href='guide.html#GUIDE5'>Inserimento del campo Coniuge</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Licenza</h2>")
document.write("<div><a href='privacy.html#PRIVACY'>Informativa sulla privacy</a></div>")
document.write("<div><a href='donate.html#DONATE'>Donazioni</a></div>")
document.write("</div>")
}