function MenuLeft() {
document.write("<div id='menu'>")
document.write("<h2>Plataforma</h2>")
document.write("<div><a href='index.html#START1'>Acerca de la plataforma</a></div>")
document.write("<div><a href='mission.html#START1'>Misión</a></div>")
document.write("<div><a href='descript.html#START2'>Descripción de la plataforma</a></div>")
document.write("<div><a href='descript.html#START3'>Requisitos técnicos</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Instalación</h2>")
document.write("<div><a href='install.html#INSTALL1'>Descarga archivo</a></div>")
document.write("<div><a href='install.html#INSTALL2'>Instalación en el sitio</a></div>")
document.write("<div><a href='install.html#INSTALL2'>Configuración del sitio</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Aplicaciones</h2>")
document.write("<div><a href='apps.html#MACOS'>MacOS, iOS</a></div>")
document.write("<div><a href='apps.html#ANDROID'>Android</a></div>")
document.write("<div><a href='apps.html#WINDOWS'>Windows</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Documentación</h2>")
document.write("<div><a href='guide.html#GUIDE1'>Introducción</a></div>")
document.write("<div><a href='guide.html#GUIDE2'>Lista de miembros de la familia</a></div>")
document.write("<div><a href='guide.html#GUIDE3'>Creación y actualización de una tarjeta</a></div>")
document.write("<div><a href='guide.html#GUIDE4'>Ingreso del campo Madre/Padre</a></div>")
document.write("<div><a href='guide.html#GUIDE5'>Ingreso del campo Cónyuge</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Licencia</h2>")
document.write("<div><a href='privacy.html#PRIVACY'>Política de Privacidad</a></div>")
document.write("<div><a href='donate.html#DONATE'>Donaciones</a></div>")
document.write("</div>")
}