function MenuLeft() {
document.write("<div id='menu'>")
document.write("<h2>Plataforma</h2>")
document.write("<div><a href='index.html#START1'>Sobre a plataforma</a></div>")
document.write("<div><a href='mission.html#START1'>Missão</a></div>")
document.write("<div><a href='descript.html#START2'>Descrição da plataforma</a></div>")
document.write("<div><a href='descript.html#START3'>Requisitos técnicos</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Instalação</h2>")
document.write("<div><a href='install.html#INSTALL1'>A descarregar o ficheiro</a></div>")
document.write("<div><a href='install.html#INSTALL2'>Instalação no site</a></div>")
document.write("<div><a href='install.html#INSTALL2'>Definições do site</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Aplicações</h2>")
document.write("<div><a href='apps.html#MACOS'>MacOS, iOS</a></div>")
document.write("<div><a href='apps.html#ANDROID'>Android</a></div>")
document.write("<div><a href='apps.html#WINDOWS'>Windows</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Documentação</h2>")
document.write("<div><a href='guia.html#GUIDE1'>Introdução</a></div>")
document.write("<div><a href='guide.html#GUIDE2'>Lista de Membros da Família</a></div>")
document.write("<div><a href='guide.html#GUIDE3'>Criar e Actualizar um Cartão</a></div>")
document.write("<div><a href='guide.html#GUIDE4'>Inserção do Campo Mãe/Pai</a></div>")
document.write("<div><a href='guide.html#GUIDE5'>Inserção do Campo Cônjuge</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Licença</h2>")
document.write("<div><a href='privacy.html#PRIVACY'>Privacidade Política</a></div>")
document.write("<div><a href='donate.html#DONATE'>Donativos</a></div>")
document.write("</div>")
}