function MenuLeft() {
document.write("<div id='menu'>")
document.write("<h2>Plateforme</h2>")
document.write("<div><a href='index.html#START1'>À propos de la plateforme</a></div>")
document.write("<div><a href='mission.html#START1'>Mission</a></div>")
document.write("<div><a href='descript.html#START2'>Description de la plateforme</a></div>")
document.write("<div><a href='descript.html#START3'>Configuration technique requise</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Installation</h2>")
document.write("<div><a href='install.html#INSTALL1'>Téléchargement archive</a></div>")
document.write("<div><a href='install.html#INSTALL2'>Installation sur le site</a></div>")
document.write("<div><a href='install.html#INSTALL2'>Paramètres du site</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Applications</h2>")
document.write("<div><a href='apps.html#MACOS'>MacOS, iOS</a></div>")
document.write("<div><a href='apps.html#ANDROID'>Android</a></div>")
document.write("<div><a href='apps.html#WINDOWS'>Windows</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Documentation</h2>")
document.write("<div><a href='guide.html#GUIDE1'>Introduction</a></div>")
document.write("<div><a href='guide.html#GUIDE2'>Liste des membres de la famille</a></div>")
document.write("<div><a href='guide.html#GUIDE3'>Créer et mettre à jour une fiche</a></div>")
document.write("<div><a href='guide.html#GUIDE4'>Saisir le champ Mère/Père</a></div>")
document.write("<div><a href='guide.html#GUIDE5'>Saisir le champ Conjoint</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Licence</h2>")
document.write("<div><a href='privacy.html#PRIVACY'>Politique de confidentialité</a></div>")
document.write("<div><a href='donate.html#DONATE'>Dons</a></div>")
document.write("</div>")
}