function MenuLeft() { 
document.write("<div id='menu'>")
document.write("<h2>Платформа</h2>")
document.write("<div><a href='index.html#START1'>О платформе</a></div>")
document.write("<div><a href='mission.html#START1'>Миссия</a></div>")
document.write("<div><a href='descript.html#START2'>Описание платформы</a></div>")
document.write("<div><a href='descript.html#START3'>Технические требования</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Установка</h2>")
document.write("<div><a href='install.html#INSTALL1'>Скачивание архива</a></div>")
document.write("<div><a href='install.html#INSTALL2'>Установка на сайт</a></div>")
document.write("<div><a href='install.html#INSTALL2'>Настройки сайта</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Приложения</h2>")
document.write("<div><a href='apps.html#MACOS'>MacOS, iOS</a></div>")
document.write("<div><a href='apps.html#ANDROID'>Android</a></div>")
document.write("<div><a href='apps.html#WINDOWS'>Windows</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Документация</h2>")
document.write("<div><a href='guide.html#GUIDE1'>Введение</a></div>")
document.write("<div><a href='guide.html#GUIDE2'>Список членов семьи</a></div>")
document.write("<div><a href='guide.html#GUIDE3'>Создание новой и обновление карточки</a></div>")
document.write("<div><a href='guide.html#GUIDE4'>Ввод поля Мать/Отец</a></div>")
document.write("<div><a href='guide.html#GUIDE5'>Ввод поля Супруг</a></div>")
document.write("<div class='line'></div>")
document.write("<h2>Лицензия</h2>")
document.write("<div><a href='privacy.html#PRIVACY'>Политика конфеденциальности</a></div>")
document.write("<div><a href='donate.html#DONATE'>Донаты</a></div>")
document.write("</div>")
}